- name: Create User Group
  become: yes
  group:
    name: "{{ item.username }}"
    state: present
  with_items: "{{ users }}"

- name: Create User Account
  become: yes
  user:
    createhome: yes
    group: "{{ item.username }}"
    name: "{{ item.username }}"
    shell: /bin/bash
    state: present
    password: "{{ admin_password_hash }}"
  with_items: "{{ users }}"
